"""
Regulatory disclaimers appended to AI responses in regulated domains.
"""

FINANCIAL_DISCLAIMER = (
    "Life OS provides financial information for educational purposes only. "
    "This is not regulated financial advice. Consult a qualified financial adviser "
    "before making investment or significant financial decisions."
)

HEALTH_DISCLAIMER = (
    "Life OS provides general health information only. "
    "This is not medical advice. Always consult a qualified healthcare professional "
    "or your GP for medical concerns, diagnoses, or treatment decisions."
)

AI_TRANSPARENCY = (
    "This response was generated by an AI model. It may contain errors. "
    "Life OS AI does not have access to real-time information."
)


def inject_disclaimer(response: "CoachResponse", domain: str) -> "CoachResponse":  # type: ignore[name-defined]
    """Append the appropriate disclaimer section to a CoachResponse."""
    from app.models.conversation import CoachSection
    disclaimer_map = {
        "finance": FINANCIAL_DISCLAIMER,
        "health": HEALTH_DISCLAIMER,
    }
    text = disclaimer_map.get(domain)
    if text:
        response.sections.append(CoachSection(type="warning", title="Disclaimer", content=text))
    return response
